### ISSUE TITLE
Unable to close the percentage box after setting the throttle bug:

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#75] opened 2020-11-17 10:43 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 
- specific aircraft in use:

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
When you go in and set your percentage, and hit ok, it doesn't close the throttle setting box.

**Comment by ajborka** [comment] 2020-11-18 02:36
@BviPilots  will take care of it when things settle down a little. Should be in the next version though.

**Comment by ajborka** [comment] 2020-11-18 02:42
duplicate of #74 .

**Closed by ajborka** 2020-11-18 02:42 UTC
