### ISSUE TITLE
Suggestion: add the ability to create a route that starts and ends at the same airport

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#89] opened 2021-01-12 19:01 UTC
I've been testing planes etc, and I thought that the ability to create route somehow (this is not aloud in sim brief  I don't think) that would allow me to start and end at the same place. So it would look something like this:

KMIA, rwy, sid, waypoint or waypoints if necessary, star,  approach, rwy, KMIA.

This could also be useful if  the end user is practicing let's say approaches, or take offs with vatsim or poscan etc.

I realize this is an odd suggestion; I hope it can be improved upon so that it is not as complex as I'm possibly making it.

**Comment by griffster94** [comment] 2021-01-13 07:26
I think personally this is a good idea. This would also be good for those who like recreational flying. Someone like me for example.

**Comment by marrie** [comment] 2021-01-14 02:07
Well, KMIA to KMIA would be an odd free flight, but for testing purposes, or practice purposes, it should be able to be done. I know that simbrief cannot do this as of now, so maybe the AIRAC data we have in the future should be able to do this in theory.e

**Comment by marrie** [comment] 2021-01-17 18:15
One correction. I said simbrief would not allow you to do this. I actually was mistaken, as I did this in another app just recently. So may I amend my suggestion that this can be done with the simbrief interface in TFM and using navigraph, or how ever that will work? Thanks.

**Comment by ajborka** [comment] 2021-08-08 21:32
duplicate of #82

**Closed by ajborka** 2021-08-08 21:32 UTC
